media:
  input: assets/uploads
  output: /assets/uploads

content:
  - name: notes
    label: 笔记
    type: collection
    path: _posts
    filename:
      template: "{year}-{month}-{day}-{title}.md"
      field: create
    format: yaml-frontmatter
    fields:
      - name: title
        label: 标题
        type: string
        required: true
      - name: description
        label: 简介
        type: text
      - name: category
        label: 分类
        type: string
      - name: body
        label: 正文
        type: rich-text
    view:
      primary: title
      fields: [title, category]
      search: [title, description]
